spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/movieDb
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  cache:
    type: redis
    host: localhost
    port: 6379
  data:
    elasticsearch:
      cluster-name: elastic-cluster
      url: https://localhost:9200
  session:
    jdbc:
      initialize-schema: always
    #store-type: jdbc
    timeout: 30m